# Generated by Django 4.0.5 on 2022-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='style',
            field=models.CharField(choices=[('a', 'm'), ('a', 'm'), ('a', 'n'), ('a', 'p'), ('a', 'p'), ('a', 'p'), ('a', 'r'), ('a', 's'), ('a', 't'), ('b', 'a'), ('c', 'x'), ('e', 'd'), ('e', 'p'), ('e', 'z'), ('g', 'i'), ('i', 'l'), ('i', 'v'), ('l', 'a'), ('l', 'a'), ('m', 'e'), ('n', 'i'), ('n', 'o'), ('o', 'b'), ('o', 'c'), ('o', 'l'), ('o', 'm'), ('o', 's'), ('o', 's'), ('r', 'a'), ('r', 'd'), ('r', 'f'), ('r', 'f'), ('r', 'f'), ('r', 'g'), ('r', 'g'), ('r', 'r'), ('r', 't'), ('s', 'v'), ('t', 's'), ('t', 's'), ('t', 's'), ('u', 'a'), ('u', 'm'), ('w', 'b')], default='friendly', max_length=100),
        ),
    ]
